name: hedis
version: 0.1.0.0
github: "culturedsys/hedis"
license: GPL-3
author: "Tim Fisken"
maintainer: "contact@timfisken.org"
copyright: "2023 Tim Fisken"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/cultredsys/hedis#readme>

dependencies:
  - base >= 4.7 && < 5
  - conduit
  - conduit-extra
  - bytestring
  - attoparsec
  - word8
  - stm
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hedis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hedis

tests:
  hedis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hedis
      - hspec
